import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import whatsappIcon from "@/app/assets/whatsapp.png";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FREEZELY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <a
          href="https://wa.me/523315350444"
          className="fixed bottom-6 right-6 z-50 flex h-14 w-14 items-center justify-center"
          aria-label="Contactar por WhatsApp"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src={whatsappIcon} alt="WhatsApp" className="h-14 w-14" />
        </a>
      </body>
    </html>
  );
}
